"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import AppNav from "@/components/AppNav";
import {useDemoAuth} from "@/lib/auth";
import {createSupabaseBrowserClient} from "@/lib/supabase/client";
type Report={id:string;topic_id:string;reply_id:string|null;reason:string;reporter_name:string;author_name:string;title:string;body:string;contains_spoilers:boolean;created_at:string};
function ReportCard({report,busy,onResolve}:{report:Report;busy:boolean;onResolve:(id:string,hide:boolean)=>void}){
 const [show,setShow]=useState(false);const [confirm,setConfirm]=useState(false);
 return <article className="space-y-3 rounded-2xl border border-white/10 bg-white/[0.03] p-5"><h2 className="text-xl font-bold">{report.title}</h2><p className="text-sm text-neutral-400">Gerapporteerd door {report.reporter_name} · {new Date(report.created_at).toLocaleString("nl-NL")}</p><p className="whitespace-pre-wrap break-words text-amber-200">{report.reason}</p><div className="rounded-xl bg-black/25 p-4"><p className="text-sm font-bold">Bericht van {report.author_name}</p>{report.contains_spoilers&&!show?<button onClick={()=>setShow(true)} className="mt-3 text-amber-200">Spoilerbericht bekijken</button>:<p className="mt-2 whitespace-pre-wrap break-words text-sm leading-7">{report.body}</p>}</div><Link className="inline-block text-sm text-cyan-200" href={`/talk-about?topic=${report.topic_id}${report.reply_id?`&reply=${report.reply_id}`:""}`}>Open gesprek →</Link><div className="flex flex-wrap gap-3"><button disabled={busy} onClick={()=>setConfirm(v=>!v)} className="rounded-lg bg-red-500/15 px-3 py-2 text-red-200">{report.reply_id?"Bericht verbergen":"Topic verbergen"}</button><button disabled={busy} onClick={()=>onResolve(report.id,false)} className="rounded-lg bg-white/10 px-3 py-2">Rapportage afwijzen</button></div>{confirm&&<div className="rounded-xl border border-red-300/20 p-3 text-sm"><p>{report.reply_id?"Dit bericht wordt onzichtbaar voor lezers. Reacties erop blijven behouden.":"Dit topic en alle bijbehorende berichten worden onzichtbaar voor lezers."}</p><button disabled={busy} onClick={()=>onResolve(report.id,true)} className="mt-3 font-bold text-red-200">Verbergen bevestigen</button></div>}</article>;
}
export default function Moderation(){const {user}=useDemoAuth();const [rows,setRows]=useState<Report[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [refresh,setRefresh]=useState(0);const [busy,setBusy]=useState(false);const guard=useRef(false);
 useEffect(()=>{let active=true;setRows([]);setLoading(true);setError("");if(user?.role!=="admin"){setLoading(false);return;}async function load(){try{const {data,error}=await createSupabaseBrowserClient().rpc("talk_admin_reports");if(error)throw error;if(active)setRows(data??[]);}catch{if(active)setError("Rapportages konden niet worden geladen.");}finally{if(active)setLoading(false);}}void load();return()=>{active=false;};},[user?.id,user?.role,refresh]);
 async function resolve(id:string,hide:boolean){if(guard.current)return;guard.current=true;setBusy(true);setError("");try{const {error}=await createSupabaseBrowserClient().rpc("talk_admin_resolve",{input_report:id,hide_content:hide});if(error)throw error;setRefresh(v=>v+1);}catch{setError("Afhandelen is niet gelukt. Vernieuw het overzicht en probeer opnieuw.");}finally{guard.current=false;setBusy(false);}}
 return <main className="min-h-screen bg-[#070a12] text-white"><AppNav title="Forumbeheer" subtitle="Talk about rapportages"/><div className="mx-auto max-w-4xl space-y-5 px-5 py-8"><Link href="/talk-about" className="text-cyan-200">← Talk about</Link><h1 className="text-3xl font-black">Gerapporteerde berichten</h1>{user?.role!=="admin"?<p>Dit overzicht is alleen toegankelijk voor admins.</p>:<><p className="text-sm text-neutral-400">De oudste 100 open rapportages staan hieronder. Na afhandeling verschijnen de volgende.</p><button onClick={()=>setRefresh(v=>v+1)} disabled={busy} className="rounded-xl bg-white/10 px-4 py-2">Vernieuwen</button>{error&&<p role="alert" className="text-red-200">{error}</p>}{loading?<p>Rapportages laden…</p>:rows.length?rows.map(r=><ReportCard key={r.id} report={r} busy={busy} onResolve={(id,hide)=>void resolve(id,hide)}/>):!error&&<p>Er zijn geen open rapportages.</p>}</>}</div></main>;
}
