"use client";
import {useState} from "react";
import type {OwnerBookShare,BookFeedbackItem,BookRevisionItem} from "@/lib/supabase/socialFeatures";
export default function BookCollaboration({bookId,shares,feedback,revisions,onRevoke,onRevision}:{bookId:string;shares:OwnerBookShare[];feedback:BookFeedbackItem[];revisions:BookRevisionItem[];onRevoke:(id:string)=>Promise<void>;onRevision:(id:string,status:"accepted"|"rejected")=>Promise<void>}){
 const [busy,setBusy]=useState(false);
 const active=shares.filter(s=>s.bookId===bookId&&s.status==="active");
 const notes=feedback.filter(f=>f.bookId===bookId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
 const proposals=revisions.filter(r=>r.bookId===bookId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
 async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);try{await action();}finally{setBusy(false)}}
 const date=(value:string)=>new Date(value).toLocaleString('nl-NL',{dateStyle:'medium',timeStyle:'short'});
 return <section className="space-y-6 border-t border-white/10 p-5 sm:p-7" aria-label="Delen, feedback en voorstellen">
 <div><h3 className="text-xl font-bold">{active.length?'Uitgeleend · gedeeld met':'Gedeeld met'}</h3><p className="mt-1 text-sm text-neutral-400">Het origineel blijft van jou en op je eigen boekenplank.</p><div className="mt-3 space-y-2">{!active.length&&<p className="text-sm text-neutral-400">Momenteel met niemand gedeeld.</p>}{active.map(s=><div key={s.shareId} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/10 p-4"><div><p className="font-bold">{s.sharedWithDisplayName}</p><p className="text-xs text-neutral-400">{s.permission==='edit'?'Lezen, feedback en bewerkingsvoorstel':s.permission==='comment'?'Lezen en feedback':'Alleen lezen'}</p></div><button disabled={busy} onClick={()=>void run(()=>onRevoke(s.shareId))} className="rounded-lg border border-red-400/30 px-3 py-2 text-sm text-red-200 disabled:opacity-40">Uitlenen annuleren</button></div>)}</div></div>
 <div><h3 className="text-xl font-bold text-yellow-200">Ontvangen feedback</h3><div className="mt-3 space-y-3">{!notes.length&&<p className="text-sm text-neutral-400">Nog geen feedback voor dit boek.</p>}{notes.map(f=><article key={f.feedbackId} className="rounded-xl border border-yellow-300/15 bg-yellow-400/5 p-4"><p className="text-sm font-bold">{f.fromDisplayName}</p><p className="mt-1 text-xs text-neutral-400">{date(f.createdAt)}{f.nodeId?` · Scène ${f.nodeId}`:''}</p><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-6">{f.message}</p></article>)}</div></div>
 <div><h3 className="text-xl font-bold text-purple-200">Bewerkingsvoorstellen</h3><div className="mt-3 space-y-3">{!proposals.length&&<p className="text-sm text-neutral-400">Nog geen voorstellen voor dit boek.</p>}{proposals.map(r=><article key={r.revisionId} className="rounded-xl border border-purple-300/15 bg-purple-400/5 p-4"><p className="font-bold">{r.editorDisplayName} · {r.status==='submitted'?'Wacht op beoordeling':r.status==='accepted'?'Geaccepteerd':'Afgewezen'}</p><p className="mt-1 text-xs text-neutral-400">{date(r.createdAt)}</p>{r.note&&<p className="mt-3 whitespace-pre-wrap break-words text-sm leading-6">{r.note}</p>}{r.status==='submitted'&&<div className="mt-3 flex gap-3"><button disabled={busy} onClick={()=>void run(()=>onRevision(r.revisionId,'accepted'))} className="rounded-lg bg-emerald-500 px-3 py-2 text-sm font-bold text-black disabled:opacity-40">Accepteren</button><button disabled={busy} onClick={()=>void run(()=>onRevision(r.revisionId,'rejected'))} className="rounded-lg border border-red-400/30 px-3 py-2 text-sm text-red-200 disabled:opacity-40">Afwijzen</button></div>}</article>)}</div></div>
 </section>;
}
