"use client";
import {createContext,useContext,useEffect,useState} from "react";
import Link from "next/link";
import {createSupabaseBrowserClient} from "@/lib/supabase/client";
export type CommunityProfile={id:string;display_name:string;author_name:string;bio:string;avatar:string;is_admin:boolean;is_author:boolean;is_exclusive:boolean};
const People=createContext<Record<string,CommunityProfile>>({});
export function ProfileBadges({profile}:{profile:CommunityProfile}){return <span className="flex flex-wrap gap-2 text-[10px] font-bold uppercase tracking-wider">{profile.is_admin&&<span className="rounded-full bg-red-500/15 px-2 py-1 text-red-200">Admin</span>}{profile.is_author&&<span className="rounded-full bg-cyan-500/15 px-2 py-1 text-cyan-200">Auteur</span>}{profile.is_exclusive&&<span className="rounded-full bg-amber-500/15 px-2 py-1 text-amber-200">Exclusive</span>}</span>;}
export function ProfileAvatar({profile,size="h-11 w-11"}:{profile:Pick<CommunityProfile,"avatar"|"display_name">;size?:string}){return profile.avatar?<img alt="" src={profile.avatar} className={`${size} shrink-0 rounded-2xl object-cover`}/>:<span className={`${size} flex shrink-0 items-center justify-center rounded-2xl bg-blue-600 font-black text-white`}>{(profile.display_name||"L").slice(0,1).toUpperCase()}</span>;}
export function CommunityPeople({ids,children}:{ids:string[];children:React.ReactNode}){const key=[...new Set(ids)].sort().join(",");const [people,setPeople]=useState<Record<string,CommunityProfile>>({});useEffect(()=>{let active=true;setPeople({});if(key)void(async()=>{try{const {data,error}=await createSupabaseBrowserClient().rpc("get_community_profiles",{input_ids:key.split(",")});if(!error&&active)setPeople(Object.fromEntries((data??[]).map((p:CommunityProfile)=>[p.id,p])));}catch{}})();return()=>{active=false;};},[key]);return <People.Provider value={people}>{children}</People.Provider>;}
export function CommunityAuthor({id,fallback}:{id:string;fallback:string}){const p=useContext(People)[id];return <Link href={`/profile/${id}`} className="inline-flex max-w-full items-center gap-3 rounded-xl hover:bg-white/5"><ProfileAvatar profile={p??{avatar:"",display_name:fallback}}/><span className="min-w-0 space-y-1"><span className="block truncate text-sm font-bold">{p?.display_name??fallback}</span>{p&&<ProfileBadges profile={p}/>}</span></Link>;}
