"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {createSupabaseBrowserClient} from "@/lib/supabase/client";
import {ProfileAvatar} from "@/components/CommunityProfile";
export default function CommunityProfileEditor({userId,name}:{userId:string;name:string}){const [bio,setBio]=useState("");const [avatar,setAvatar]=useState("");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const guard=useRef(false);const [loadError,setLoadError]=useState(false);const [retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);setLoadError(false);void(async()=>{try{const {data,error}=await createSupabaseBrowserClient().rpc("get_community_profiles",{input_ids:[userId]});if(error)throw error;if(active){setBio(data?.[0]?.bio??"");setAvatar(data?.[0]?.avatar??"");}}catch{if(active){setLoadError(true);setMessage("Je openbare profiel kon niet worden geladen.");}}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[userId,retry]);
 async function upload(file?:File){if(!file||guard.current)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024){setMessage("Kies een JPG, PNG of WebP van maximaal 8 MB.");return;}guard.current=true;setBusy(true);setMessage("");try{const bitmap=await createImageBitmap(file);const canvas=document.createElement("canvas");canvas.width=256;canvas.height=256;const ctx=canvas.getContext("2d");if(!ctx)throw Error();ctx.fillStyle='#111827';ctx.fillRect(0,0,256,256);const side=Math.min(bitmap.width,bitmap.height);ctx.drawImage(bitmap,(bitmap.width-side)/2,(bitmap.height-side)/2,side,side,0,0,256,256);bitmap.close();const value=canvas.toDataURL('image/jpeg',0.82);if(value.length>180000)throw Error();setAvatar(value);setMessage("Voorbeeld bijgewerkt. Klik op Openbaar profiel opslaan.");}catch{setMessage("Deze afbeelding kon niet worden verwerkt. Probeer een andere afbeelding.");}finally{guard.current=false;setBusy(false);}}
 async function save(){if(guard.current||loading||loadError)return;guard.current=true;setBusy(true);setMessage("");try{const {error}=await createSupabaseBrowserClient().rpc('save_community_profile',{input_bio:bio,input_avatar:avatar});if(error)throw error;setMessage("Je openbare profiel is opgeslagen.");}catch{setMessage("Opslaan is niet gelukt. Je aanpassingen blijven hier staan.");}finally{guard.current=false;setBusy(false);}}
 return <section className="mt-7 space-y-4 border-t border-white/10 pt-6"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-lg font-black">Openbaar profiel</h3><Link href={`/profile/${userId}`} className="text-sm text-cyan-200">Bekijk mijn profiel →</Link></div><p className="text-sm leading-6 text-neutral-400">Je naam, auteursnaam, avatar, bio, badges en gepubliceerde boeken zijn zichtbaar voor iedereen. Je e-mail, abonnement en accountinstellingen blijven privé.</p>{loading?<p>Profiel laden…</p>:loadError?<button onClick={()=>setRetry(v=>v+1)} className="text-cyan-200">Opnieuw proberen</button>:<fieldset disabled={busy} className="space-y-4"><div className="flex flex-wrap items-center gap-4"><ProfileAvatar profile={{avatar,display_name:name}} size="h-24 w-24"/><div><label className="block text-sm font-bold">Avatar kiezen<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}} className="mt-2 block w-full max-w-64 text-xs"/></label><p className="mt-2 text-xs text-neutral-500">Vierkante uitsnede · JPG, PNG of WebP · maximaal 8 MB</p>{avatar&&<button onClick={()=>setAvatar("")} className="mt-2 text-xs text-red-200">Avatar verwijderen</button>}</div></div><label className="block text-sm font-bold">Over mij<textarea rows={4} maxLength={1000} value={bio} onChange={e=>setBio(e.target.value)} className="mt-2 block w-full rounded-xl border border-white/10 bg-black/35 p-3" placeholder="Vertel over jezelf en de boeken die je leest of schrijft."/></label><p className="text-xs text-neutral-500">{bio.length}/1000 tekens</p><button onClick={()=>void save()} className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold">{busy?"Bezig…":"Openbaar profiel opslaan"}</button></fieldset>}{message&&<p role="status" className="text-sm text-cyan-100">{message}</p>}</section>;
}
