"use client";
import {useRef,useState} from "react";
import {createSupabaseBrowserClient} from "@/lib/supabase/client";
export default function TalkEditPost({post,isTopic,onSaved}:{post:{id:string;body:string;title?:string;contains_spoilers:boolean};isTopic:boolean;onSaved:()=>void}){
 const [open,setOpen]=useState(false);const [body,setBody]=useState(post.body);const [title,setTitle]=useState(post.title??"");const [spoilers,setSpoilers]=useState(post.contains_spoilers);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const guard=useRef(false);
 async function save(e:React.FormEvent){e.preventDefault();if(guard.current)return;guard.current=true;setBusy(true);setError("");try{const {error}=await createSupabaseBrowserClient().rpc("talk_edit_post",{input_id:post.id,is_topic:isTopic,input_body:body,input_spoilers:spoilers,input_title:isTopic?title:null});if(error)throw error;setOpen(false);onSaved();}catch{setError("Opslaan is niet gelukt. Je tekst blijft hier staan. Controleer of het topic nog open is en probeer opnieuw.");}finally{guard.current=false;setBusy(false);}}
 const field="mt-2 block w-full rounded-xl border border-white/20 bg-[#111827] p-3 text-white";
 return <div className="mt-3">{!open?<button className="text-sm text-cyan-200" onClick={()=>{setBody(post.body);setTitle(post.title??"");setSpoilers(post.contains_spoilers);setError("");setOpen(true);}}>Bewerken</button>:<form onSubmit={save} className="space-y-3 rounded-xl border border-cyan-300/25 p-4"><h3 className="font-bold">Bericht bewerken</h3><fieldset disabled={busy} className="space-y-3">{isTopic&&<label className="block text-sm">Titel<input className={field} required minLength={3} maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label>}<label className="block text-sm">Bericht<textarea autoFocus className={field} required maxLength={8000} rows={6} value={body} onChange={e=>setBody(e.target.value)}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={spoilers} onChange={e=>setSpoilers(e.target.checked)}/>Bevat spoilers</label>{error&&<p role="alert" className="text-sm text-red-200">{error}</p>}<div className="flex gap-4"><button className="rounded-lg bg-cyan-500/15 px-3 py-2 text-cyan-200">{busy?"Opslaan…":"Opslaan"}</button><button type="button" onClick={()=>setOpen(false)}>Annuleren</button></div></fieldset></form>}</div>;
}
