"use client";
import {useEffect,useState} from "react";
import {useParams} from "next/navigation";
import Link from "next/link";
import AppNav from "@/components/AppNav";
import {CommunityProfile,ProfileAvatar,ProfileBadges} from "@/components/CommunityProfile";
import {createSupabaseBrowserClient} from "@/lib/supabase/client";
import {useDemoAuth} from "@/lib/auth";
type Book={id:string;title:string;cover_image:string;author:string};
export default function ProfilePage(){const {userId}=useParams<{userId:string}>();const {user}=useDemoAuth();const [profile,setProfile]=useState<CommunityProfile|null>(null);const [books,setBooks]=useState<Book[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setProfile(null);setBooks([]);setLoading(true);setError("");void(async()=>{try{if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(userId))return;const db=createSupabaseBrowserClient();const [p,b]=await Promise.all([db.rpc('get_community_profiles',{input_ids:[userId]}),db.rpc('get_community_books',{input_user:userId})]);if(p.error||b.error)throw p.error||b.error;if(active){setProfile(p.data?.[0]??null);setBooks(b.data??[]);}}catch{if(active)setError("Dit profiel kon niet worden geladen.");}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[userId,retry]);
 return <main className="min-h-screen bg-[#070a12] text-white"><AppNav title="Profiel" subtitle="De mensen achter de verhalen"/><div className="mx-auto max-w-5xl space-y-8 px-5 py-10">{loading?<p>Profiel laden…</p>:error?<div role="alert"><p>{error}</p><button className="mt-3 text-cyan-200" onClick={()=>setRetry(v=>v+1)}>Opnieuw proberen</button></div>:!profile?<h1 className="text-2xl font-bold">Profiel niet gevonden</h1>:<><section className="rounded-3xl border border-cyan-300/15 bg-gradient-to-br from-blue-950/40 to-white/[0.025] p-6 sm:p-9"><div className="flex flex-wrap items-center gap-5"><ProfileAvatar profile={profile} size="h-28 w-28"/><div className="min-w-0 flex-1"><p className="text-xs uppercase tracking-widest text-cyan-200">DiBooks community</p><h1 className="my-2 break-words text-3xl font-black sm:text-4xl">{profile.display_name}</h1>{profile.author_name&&profile.author_name!==profile.display_name&&<p className="mb-3 text-sm text-neutral-400">Auteursnaam: {profile.author_name}</p>}<ProfileBadges profile={profile}/></div>{user?.id===userId&&<Link href="/account" className="rounded-xl border border-white/15 px-4 py-3 text-sm font-bold">Mijn profiel aanpassen</Link>}</div><p className="mt-6 whitespace-pre-wrap break-words leading-7 text-neutral-300">{profile.bio||"Deze lezer heeft nog geen bio toegevoegd."}</p></section><section><h2 className="mb-5 text-2xl font-black">Gepubliceerde boeken</h2>{!books.length?<p className="text-neutral-400">Nog geen gepubliceerde boeken.</p>:<div className="grid grid-cols-2 gap-5 sm:grid-cols-3 lg:grid-cols-4">{books.map(b=><Link key={b.id} href={`/books/${b.id}`} className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03] hover:border-cyan-300/40">{b.cover_image?<img alt={`Cover van ${b.title}`} src={b.cover_image} className="aspect-[2/3] w-full object-cover"/>:<div className="flex aspect-[2/3] items-center justify-center bg-blue-950 p-4 text-center font-bold">{b.title}</div>}<div className="p-4"><h3 className="break-words font-bold">{b.title}</h3><p className="mt-1 text-xs text-neutral-400">{b.author}</p></div></Link>)}</div>}</section></>}</div></main>;
}
